Add Pundit
jt-is-coding/industrial-auth-1 pull request #2
Opened 2024-07-19 19:48 UTC by jt-is-coding

2024-07-19 20:06 UTC, Cindellai approved these changes

2024-07-19 20:06 UTC, Cindellai commented on app/controllers/application_controller.rb
> +  include Pundit
good job remembering to include pundit

2024-07-19 20:06 UTC, Cindellai commented on app/policies/comment_policy.rb
> +    update?
good job reusing methods

2024-07-19 20:06 UTC, Cindellai commented on app/views/users/show.html.erb
> +<% if policy(@user).show? %>
code looks good

2024-07-23 17:31 UTC, ajmompr requested changes
Fantastic start. Fix your user policy and users#show page then you should be good to go

2024-07-23 17:31 UTC, ajmompr commented on app/controllers/comments_controller.rb
> +  before_action { authorize(@comment || Comment) }
good

2024-07-23 17:31 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
> +  before_action { authorize(@follow_request || FollowRequest) }
good

2024-07-23 17:31 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +  before_action { authorize(@photo || Photo) }
good

2024-07-23 17:31 UTC, ajmompr commented on app/controllers/photos_controller.rb
>    before_action :ensure_current_user_is_owner, only: [:destroy, :update, :edit]
redundant since you are authorizing on line 4. remove this

2024-07-23 17:31 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +    authorize @photo
redundant if you call authorize before action

2024-07-23 17:31 UTC, ajmompr commented on app/controllers/users_controller.rb
> +  before_action { authorize(@user || User )}
perfect

2024-07-23 17:31 UTC, ajmompr commented on app/policies/user_policy.rb
> +    user == current_user || !user.private? || user.followers.include?(current_user)
almost. set to true and move this logic to show_photos? Then make sure to call this policy in your users#show

2024-07-23 17:31 UTC, ajmompr commented on app/views/users/show.html.erb
> +<% if policy(@user).show? %>
This policy should be .show_photos? to account for edge case/private accounts

2024-07-24 13:49 UTC, ajmompr approved these changes
good job!

2024-07-24 13:56 UTC, merged